sudo: false

addons:
    apt_packages:
        - lib32stdc++6

env: 
  global:
    - INCLUDE=addons/sourcemod/scripting/include/
    - SCRIPTING=addons/sourcemod/scripting/
    - PLUGINS=addons/sourcemod/plugins/
    - HOME=ftp.toastdev.de/plugins

before_install:
  - mkdir build-env

install:
  - cd build-env
  - wget https://sm.alliedmods.net/smdrop/1.10/sourcemod-1.10.0-git6405-linux.tar.gz
  - tar -xzvf sourcemod-1.10.0-git6405-linux.tar.gz
  - cd ../
  - find build-env/addons/sourcemod/scripting/ -name "*.sp" -type f -delete
  - cp -rv $SCRIPTING/. build-env/addons/sourcemod/scripting/
  - cp -rv $INCLUDE/. build-env/addons/sourcemod/scripting/include/

before_script:
  - chmod +rx build-env/addons/sourcemod/scripting/spcomp
  - chmod +rx build-env/addons/sourcemod/scripting/compile.sh
  - cd build-env/addons/sourcemod/scripting/
  
script:
  - ./compile.sh